### ISSUE TITLE
This is a great project. When will the code be released

### ISSUE THREAD

**Issue by zhanghongyong123456** [bcmi/CDTNet-High-Resolution-Image-Harmonization#1]

**Comment by zhanghongyong123456** [comment]
> _No description provided._

很不幸的看到您的源码以及模型不能发布，请问这个模型的效果如何呢，主要包括两方面：1.能对多大分辨率图像进行和谐化，4k可以实现吗？  2. 处理视频的话，fps 能达到多少，是否可以达到4k 实时（30 fps），期待您的回复

**Comment by ustcnewly** [comment]
4K没问题，可以做到实时

**Comment by zhanghongyong123456** [comment]
> 4K没问题，可以做到实时

您好，谢谢您的及时，请问主要是
![image](https://user-images.githubusercontent.com/48466610/157188605-38a65998-c4e1-4d0d-b24d-bc7a4b4f2962.png)
借鉴了这两个项目实现的吗，

**Comment by ustcnewly** [comment]
是的

**Comment by zhanghongyong123456** [comment]
> 是的

您好，我在看您的论文，我i想知道这一步是什么操作
![image](https://user-images.githubusercontent.com/48466610/157815422-3cd2fa6f-5bf9-416d-906f-605211ee72b4.png)
这个是推理时间吗，是在什么设备下测试的，我想知道什么样的设备下可以实现 3840*2160 图像 达到30fps
![image](https://user-images.githubusercontent.com/48466610/157815534-97ab9430-3b3f-4cd4-ad3c-cfda0220027c.png)

**Comment by ustcnewly** [comment]
是inference time, 设备在paper里面应该写了。

**Comment by Mia-Cong** [comment]
> 

这一步是利用下采样的mask和bottleneck feature，分别得到前景和背景的特征并进行拼接，拼接后的特征会用于预测LUT的组合系数。
![ans](https://user-images.githubusercontent.com/45754293/158974902-f568060e-52a3-4a37-b725-6a22f2720630.png)

**Comment by smandal94** [comment]
Is there a timeline for code release?
