### ISSUE TITLE
Request test results

### ISSUE THREAD

**Issue by dorianzhang7** [bcmi/CDTNet-High-Resolution-Image-Harmonization#10]
Dear author, I am doing a comparative test recently, and I need the test results of your model, but I noticed that the online disk link of 256X256 on the iHarmony4 test set is broken, could you update it again? Thank you very much for receiving your reply!

**Comment by taoxinhao13** [comment]
Hello, thank you for following our work. The link is dead due to several images being mistaken for illegal images. I have updated the link, and it's a zip file and can download now.
