### ISSUE TITLE
There is no pre-trained model on 1024×1024 HAdobe5k

### ISSUE THREAD

**Issue by Hikari6666** [bcmi/CDTNet-High-Resolution-Image-Harmonization#11]
Or I should also use the model HAdobe5k_2048.pth？I want to look at some data such as the running time and memory cost，I think it should be tested on the same device to make a fair comparison，is that right？

**Comment by taoxinhao13** [comment]
You can use the torchstat library to test memory usage, FLOPs, and some other parameters. For more detailed information, please visit [https://github.com/Swall0w/torchstat](https://github.com/Swall0w/torchstat). It is important to note that the inference time of a model is not contingent on its parameters; rather, it is significantly influenced by the current gpu.
