### ISSUE TITLE
ModuleNotFoundError: No module named 'trilinear'

### ISSUE THREAD

**Issue by JerryTT2019** [bcmi/CDTNet-High-Resolution-Image-Harmonization#14]
Hi！
lut.py中的"import trilinear" 是一个python库吗，清华源中的[trilinear-2.1.tar.gz]点进去是404，其他镜像站也没找到这个库

**Comment by taoxinhao13** [comment]
您好，您可以参考 https://github.com/HuiZeng/Image-Adaptive-3DLUT 中的流程来进行编译，这个库无法直接pip
