### ISSUE TITLE
您好，可以更新一下百度云链接吗，这几个全部失效了

### ISSUE THREAD

**Issue by zhanghongyong123456** [bcmi/CDTNet-High-Resolution-Image-Harmonization#4]
![2022-04-01 10-25-26屏幕截图](https://user-images.githubusercontent.com/48466610/161182977-ff60cd39-6368-434b-b525-7446898814e6.png)
![2022-04-01 10-25-34屏幕截图](https://user-images.githubusercontent.com/48466610/161182985-d5d81913-dbec-4a17-880d-704c8ec46c5b.png)

**Comment by ustcnewly** [comment]
链接已更新。
