### ISSUE TITLE
The download link for the Results seems failed

### ISSUE THREAD

**Issue by WindVChen** [bcmi/CDTNet-High-Resolution-Image-Harmonization#5]
Hi, 

It's a nice work. I hope to make use of your results for visualization comparisons, but the current download link seems failed. Would you mind re-opening the download link for test results on both the HAdobe5K and the 100 Real Composite Images?

**Comment by ustcnewly** [comment]
Thanks for your attention. We have updated the download links.

**Comment by WindVChen** [comment]
@ustcnewly Thanks for providing the data. However, I still fail to access the download link of "High-resolution (1024×1024 and 2048×2048) results on HAdobe5k test set". Seems to be due to visitor limit.
![image](https://user-images.githubusercontent.com/56162412/175012875-ef3652ea-fa9b-4cbf-9040-10e368eaa37b.png)

**Comment by ustcnewly** [comment]
done

**Comment by WindVChen** [comment]
@ustcnewly Very sorry to interrupt again. Could I go further for the original background images and the foreground images in "100 High-Resolution Real Composite Images"? It seems that only the final composited images and the corresponding masks are included in the provided 100-real-dataset.

Sorry again for my interruption, and looking forward to your reply.
