### ISSUE TITLE
关于训练设置

### ISSUE THREAD

**Issue by Hikari6666** [bcmi/CDTNet-High-Resolution-Image-Harmonization#7]
请问在训练的时候，关于LUT的相关参数设置，以及epoch设置，大概训练了多久呢？另外关于Light-weighted Refinement模块，我也是写了简单的两层卷积，但是在测试的时候发现图片都已经不是正常的拍摄图，内容没变，只是颜色外观扭曲了，所以想问下关于这个模块的详细信息，谢谢

**Comment by taoxinhao13** [comment]
训练100个epoch就差不多了，当然其实几个epoch开始就已经有效果了，后续收敛较慢；这个模块是两层卷积+blending layer的结构，对应的blending layer可以参考https://github.com/saic-vul/image_harmonization，没有blending layer会差很多，这个我们在消融实验中也有所提及

**Comment by taoxinhao13** [comment]
@Hikari6666 训练100个epoch就差不多了，当然其实几个epoch开始就已经有效果了，后续收敛较慢；这个模块是两层卷积+blending layer的结构，对应的blending layer可以参考[https://github.com/saic-vul/image_harmonization](https://github.com/saic-vul/image_harmonization%EF%BC%8C%E6%B2%A1%E6%9C%89blending) ，没有blending layer会差很多，这个我们在消融实验中也有所提及

**Comment by Hikari6666** [comment]
好的我知道了，原来这个blending layer才是问题的关键。我在复现的时候选取了我之前使用过的低分辨率网络结构，想着先看下结果，因为我记得有说可以选取任意的低分辨率和谐化网络来着，所以并没有注意到这里，看消融实验的时候没有太在意数据差距。我现在实验的结果确实很符合消融实验的结果QAQ，十分感谢您的回复&nbsp;


6民
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月28日(星期五) 晚上10:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bcmi/CDTNet-High-Resolution-Image-Harmonization] 关于训练设置 (Issue #7)





 
训练100个epoch就差不多了，当然其实几个epoch开始就已经有效果了，后续收敛较慢；这个模块是两层卷积+blending layer的结构，对应的blending layer可以参考https://github.com/saic-vul/image_harmonization，没有blending layer会差很多，这个我们在消融实验中也有所提及

**Comment by taoxinhao13** [comment]
@Hikari6666 不用客气，祝你学业顺利
