### ISSUE TITLE
最后协调后的图片是否会改变背景颜色

### ISSUE THREAD

**Issue by XavierYu404** [bcmi/CDTNet-High-Resolution-Image-Harmonization#9]
您好！
模型最后的混合层输出时并没有利用mask来限制协调区域，那最后是否会影响到原图的背景呢？

**Comment by taoxinhao13** [comment]
blending layer的学习使得网络对背景的影响极小(小数点后几位)，以至于到转为图片要离散到0-255后就不改变了
